### ISSUE TITLE
it crashes randomly is it because i have 36 mods

### ISSUE THREAD

**Issue by gdmulon** [geode-sdk/geode#372]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

i forgor

### Mods Installed

36 mods i dont wanna cite them all

### Steps to Reproduce

i did creating in the editor

### Additional Information

**### _this is likely to happen because of my ### **mods_**__**

**Comment by Alphatism** [comment]
You gave absolutely NO information for us to help. No crash logs, no geode version, no mod list, nothing. No one can help without those. And in your additional information, you stated it’s most likely due to one of your mods, then why report it here, this is for **Geode** issues, not specific mod issues.

**Comment by Capeling** [comment]
If you find out what mod it was create an issue report on that mods repository
