### ISSUE TITLE
Repeats "Unzipping Index" infinitely when on the download tab of the Geode menu

### ISSUE THREAD

**Issue by andygun111** [geode-sdk/geode#445]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0-beta.7

### Expected Behavior

Expected to view available mods.

### Actual Behavior

Infinitely loops through these messages:

"
Checking Status
Beginning Download
Downloading
Unzipping Index
"

### Steps to Reproduce

1) Click on the Geode icon on the main menu
2) Go into the download tab

### Additional Information

Not sure if I'm just being too impatient but I've waited around 5 minutes and it keeps doing this.

**Comment by altalk23** [comment]
cant reproduce, also do you still get this in beta 9

**Comment by andygun111** [comment]
Technically it's not happening anymore, but in it's place it's producing an error message/popup/window

**Comment by Potatosei** [comment]
i did it somehow, it was working fine at first, then mods stopped loading when i customized an OpenHack keybind and OpenHack started crashing, so i uninstalled it, when i got back in geometry dash, it was forever updating local cache instead of unzipping index

![Screenshot (171)](https://github.com/geode-sdk/geode/assets/140474345/cf609589-1428-441a-a146-a033e7241317)
