### ISSUE TITLE
No iPhone download.

### ISSUE THREAD

**Issue by GeomatryDash** [geode-sdk/geode#598]
### Geode Version

Beta

### Related Problem

It’s frustrating to know that is is not on iPhone.

### Your Solution

If you could put it on iPhone that would be great.

**Comment by Rustring** [comment]
iPhone support is impossible according to the creator of iCreate Pro

**Comment by RoootTheFox** [comment]
Yes, it is in fact not possible with out a jailbreak due to Apple's strict policies of what you can do on iOS. Geode heavily relies on loading native libraries at runtime (read: mods), which Apple fully forbids. Only way to get around this is by jailbreaking, and even then there's going to be mire technical difficulties and annoyances for supporting iOS.

**tldr;** iOS support won't be happening, because iOS doesn't allow stuff that Geode needs to work.
