### ISSUE TITLE
Doesn't automatically restart

### ISSUE THREAD

**Issue by wwwbfjxisiuz** [geode-sdk/geode#658]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Windows

### Geode Version

v2.0.0-beta.23

### Mods Installed

geode.backup v1.0.5
geode.betterpause v1.6.8
geode.coinsinpausemenu v1.1.2
geode.customkeybinds v1.5.2
geode.entersearch v1.6.9
geode.hidepausebutton v1.2.0
geode.levelthumnails v1.0.3
geode.nodeids v1.8.1
geode.wavetrailglowy v1.0.0
geode.megahackpro v8.0.0

### Expected Behavior

Whenever I update or install new mods, I want it to restart and automatically back to the game.

### Actual Behavior

![螢幕擷取畫面 (115)](https://github.com/geode-sdk/geode/assets/76027861/cd4ae0a1-a9f1-44eb-8d14-3c45e912b53d)
![螢幕擷取畫面 (116)](https://github.com/geode-sdk/geode/assets/76027861/b895d78f-0a93-446f-aaf3-bf5b889b0617)
After clicking those, I have to open the game manually.

### Steps to Reproduce

By clicking the pink restart button.

### Additional Information

I have deleted and reinstalled the whole GD & Geode files once before, but it kept happening.

**Comment by RayDeeUx** [comment]
i have 240 mods installed (220+ active) and get this once in a while. from personal experience i would recommend having a few apps open possible to avoid running into this issue.

also, you seem to have edited the mod IDs.

**Comment by xparadoxical** [comment]
I can repro this most of the time when restarting using khronophobia.shortcuts_menu. The log window stays visible for several seconds after the game window was closed. Maybe it's something to do with saving? Also I don't remember this happening a few months ago, restarting didn't use to be an issue.

**Comment by RayDeeUx** [comment]
@xparadoxical let me explain why this is difficult to reproduce:

> I can repro this most of the time when restarting using khronophobia.shortcuts_menu

This is the relevant line of code responsible for restarting the game from `khronophobia.shortcuts_menu`:
https://github.com/Khronophobia/Shortcuts-Menu/blob/main/src/ShortcutsPopup.cpp#L552

You can also see this same line of code in these two repositories: 
https://github.com/Weebifying/restartbutton-geode/blob/main/src/main.cpp#L15
https://github.com/geode-sdk/geode/blob/main/loader/src/ui/internal/list/ModListCell.cpp#L262

All three of these lines of code call the same function from within Geode itself. `khronophobia.shortcuts_menu` by itself isn't causing the issue, and more importantly, @wwwbfjxisiuz's mod list doesn't include any mention of `shortcuts_menu` (edited mod IDs or otherwise).

> Also I don't remember this happening a few months ago, restarting didn't use to be an issue.

Given the three links I just shared, the issue clearly originates from some change within Geode's restart code itself (and not from `khronophobia.shortcuts_menu` or any specific mod); I could hypothetically publish an entirely new mod that also calls Geode's `utils::game::restart();` function and run into this issue sooner or later.

**Comment by xparadoxical** [comment]
I didn't say it's *caused* by the mod I mentioned, just wanted to share a quicker way to restart than installing/updating/removing a mod

**Comment by matcool** [comment]
stale, reopen if needed

**Comment by xparadoxical** [comment]
this stopped happening at some point and never happened to me again, probably it's fixed

**Comment by wwwbfjxisiuz** [comment]
> this stopped happening at some point and never happened to me again, probably it's fixed

You're right. I hope this problem is done and will be gone forever.
