### ISSUE TITLE
[Bug] Geode download loader resources on every restart

### ISSUE THREAD

**Issue by EMREOYUN** [geode-sdk/geode#707]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android64

### Geode Version

v2.0.0-beta.24

### Expected Behavior

The game starts normally after downloading the resources downloaded once.

### Actual Behavior

Every time you start the game, the resources will downloaded, regardless of whether the files downloaded before.

### Steps to Reproduce

1) Launch the game from android.

**Comment by jenca-adam** [comment]
I have this issue too.
It seems to occur on old/bad android phones and it happens with normal GD(it doesnt save data).
I think this is an issue with the cocos engine since it happens in every single gd game (at least for me) and the engine is so old and niche you can expect to have quite a few bugs on certain platforms.
I havent looked into this too much though.

**Comment by jenca-adam** [comment]
Do you have a multi-user environment on your device?

Cocos's `CCFileUtils::getWritablePath` doesnt seem to work with it.

**Comment by EMREOYUN** [comment]
> Do you have a multi-user environment on your device?
> 
> Cocos's `CCFileUtils::getWritablePath` doesnt seem to work with it.

Negative, I'm the only user on the device. Any feature that allows mutliple data partitions(multi-user, second space, etc.) are disabled.

**Comment by EMREOYUN** [comment]
Fixed in v2.0.0-beta25
